// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package jamesburvelocallaghaniiicitibankdemobusinessinc

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/stainless-sdks/1231-go/internal/apijson"
	"github.com/stainless-sdks/1231-go/internal/apiquery"
	"github.com/stainless-sdks/1231-go/internal/param"
	"github.com/stainless-sdks/1231-go/internal/requestconfig"
	"github.com/stainless-sdks/1231-go/option"
)

// AIAdService contains methods and other services that help with interacting with
// the 1231 API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewAIAdService] method instead.
type AIAdService struct {
	Options  []option.RequestOption
	Generate *AIAdGenerateService
}

// NewAIAdService generates a new service that applies the given options to each
// request. These options are applied after the parent client's options (if there
// is one), and before any request-specific options.
func NewAIAdService(opts ...option.RequestOption) (r *AIAdService) {
	r = &AIAdService{}
	r.Options = opts
	r.Generate = NewAIAdGenerateService(opts...)
	return
}

// Retrieves a list of all video advertisements previously generated by the user in
// the AI Ad Studio.
func (r *AIAdService) ListGenerated(ctx context.Context, query AIAdListGeneratedParams, opts ...option.RequestOption) (res *AIAdListGeneratedResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "ai/ads"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return
}

// Polls the real-time status of an asynchronous video generation operation. Once
// complete ('done'), the response includes a temporary, signed URL to access and
// download the generated video asset.
func (r *AIAdService) GetStatus(ctx context.Context, operationID interface{}, opts ...option.RequestOption) (res *VideoOperationStatus, err error) {
	opts = slices.Concat(r.Options, opts)
	path := fmt.Sprintf("ai/ads/operations/%v", operationID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return
}

type VideoOperationStatus struct {
	ErrorMessage       string                     `json:"errorMessage"`
	Message            string                     `json:"message"`
	OperationID        string                     `json:"operationId"`
	PreviewImageUri    string                     `json:"previewImageUri" format:"uri"`
	ProgressPercentage int64                      `json:"progressPercentage"`
	Status             VideoOperationStatusStatus `json:"status"`
	VideoUri           string                     `json:"videoUri" format:"uri"`
	JSON               videoOperationStatusJSON   `json:"-"`
}

// videoOperationStatusJSON contains the JSON metadata for the struct
// [VideoOperationStatus]
type videoOperationStatusJSON struct {
	ErrorMessage       apijson.Field
	Message            apijson.Field
	OperationID        apijson.Field
	PreviewImageUri    apijson.Field
	ProgressPercentage apijson.Field
	Status             apijson.Field
	VideoUri           apijson.Field
	raw                string
	ExtraFields        map[string]apijson.Field
}

func (r *VideoOperationStatus) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r videoOperationStatusJSON) RawJSON() string {
	return r.raw
}

type VideoOperationStatusStatus string

const (
	VideoOperationStatusStatusQueued     VideoOperationStatusStatus = "queued"
	VideoOperationStatusStatusGenerating VideoOperationStatusStatus = "generating"
	VideoOperationStatusStatusRendering  VideoOperationStatusStatus = "rendering"
	VideoOperationStatusStatusDone       VideoOperationStatusStatus = "done"
	VideoOperationStatusStatusError      VideoOperationStatusStatus = "error"
)

func (r VideoOperationStatusStatus) IsKnown() bool {
	switch r {
	case VideoOperationStatusStatusQueued, VideoOperationStatusStatusGenerating, VideoOperationStatusStatusRendering, VideoOperationStatusStatusDone, VideoOperationStatusStatusError:
		return true
	}
	return false
}

type AIAdListGeneratedResponse struct {
	Data []VideoOperationStatus        `json:"data"`
	JSON aiAdListGeneratedResponseJSON `json:"-"`
	PaginatedList
}

// aiAdListGeneratedResponseJSON contains the JSON metadata for the struct
// [AIAdListGeneratedResponse]
type aiAdListGeneratedResponseJSON struct {
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *AIAdListGeneratedResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r aiAdListGeneratedResponseJSON) RawJSON() string {
	return r.raw
}

type AIAdListGeneratedParams struct {
	// The maximum number of items to return.
	Limit param.Field[int64] `query:"limit"`
	// The number of items to skip before starting to collect the result set.
	Offset param.Field[int64] `query:"offset"`
	// Filter ads by their generation status.
	Status param.Field[AIAdListGeneratedParamsStatus] `query:"status"`
}

// URLQuery serializes [AIAdListGeneratedParams]'s query parameters as
// `url.Values`.
func (r AIAdListGeneratedParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

// Filter ads by their generation status.
type AIAdListGeneratedParamsStatus string

const (
	AIAdListGeneratedParamsStatusQueued     AIAdListGeneratedParamsStatus = "queued"
	AIAdListGeneratedParamsStatusGenerating AIAdListGeneratedParamsStatus = "generating"
	AIAdListGeneratedParamsStatusDone       AIAdListGeneratedParamsStatus = "done"
	AIAdListGeneratedParamsStatusError      AIAdListGeneratedParamsStatus = "error"
)

func (r AIAdListGeneratedParamsStatus) IsKnown() bool {
	switch r {
	case AIAdListGeneratedParamsStatusQueued, AIAdListGeneratedParamsStatusGenerating, AIAdListGeneratedParamsStatusDone, AIAdListGeneratedParamsStatusError:
		return true
	}
	return false
}
