// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package jocall3

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/jocall3/go/internal/apijson"
	"github.com/jocall3/go/internal/apiquery"
	"github.com/jocall3/go/internal/param"
	"github.com/jocall3/go/internal/requestconfig"
	"github.com/jocall3/go/option"
)

// AIAdService contains methods and other services that help with interacting with
// the jocall3 API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewAIAdService] method instead.
type AIAdService struct {
	Options  []option.RequestOption
	Generate *AIAdGenerateService
}

// NewAIAdService generates a new service that applies the given options to each
// request. These options are applied after the parent client's options (if there
// is one), and before any request-specific options.
func NewAIAdService(opts ...option.RequestOption) (r *AIAdService) {
	r = &AIAdService{}
	r.Options = opts
	r.Generate = NewAIAdGenerateService(opts...)
	return
}

// Retrieves a list of all video advertisements previously generated by the user in
// the AI Ad Studio.
func (r *AIAdService) ListGenerated(ctx context.Context, query AIAdListGeneratedParams, opts ...option.RequestOption) (res *AIAdListGeneratedResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "ai/ads"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return
}

// Polls the real-time status of an asynchronous video generation operation. Once
// complete ('done'), the response includes a temporary, signed URL to access and
// download the generated video asset.
func (r *AIAdService) GetStatus(ctx context.Context, operationID interface{}, opts ...option.RequestOption) (res *VideoOperationStatus, err error) {
	opts = slices.Concat(r.Options, opts)
	path := fmt.Sprintf("ai/ads/operations/%v", operationID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return
}

type VideoOperationStatus struct {
	// A descriptive status message.
	Message interface{} `json:"message,required"`
	// The unique identifier for the video generation operation.
	OperationID interface{} `json:"operationId,required"`
	// Estimated completion percentage (0-100).
	ProgressPercentage interface{} `json:"progressPercentage,required"`
	// Current status of the video generation job.
	Status VideoOperationStatusStatus `json:"status,required"`
	// Error message if the operation failed.
	ErrorMessage interface{} `json:"errorMessage"`
	// Temporary, signed URL to a preview image/thumbnail of the video.
	PreviewImageUri interface{} `json:"previewImageUri"`
	// Temporary, signed URL to the generated video asset (available when status is
	// 'done').
	VideoUri interface{}              `json:"videoUri"`
	JSON     videoOperationStatusJSON `json:"-"`
}

// videoOperationStatusJSON contains the JSON metadata for the struct
// [VideoOperationStatus]
type videoOperationStatusJSON struct {
	Message            apijson.Field
	OperationID        apijson.Field
	ProgressPercentage apijson.Field
	Status             apijson.Field
	ErrorMessage       apijson.Field
	PreviewImageUri    apijson.Field
	VideoUri           apijson.Field
	raw                string
	ExtraFields        map[string]apijson.Field
}

func (r *VideoOperationStatus) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r videoOperationStatusJSON) RawJSON() string {
	return r.raw
}

// Current status of the video generation job.
type VideoOperationStatusStatus string

const (
	VideoOperationStatusStatusQueued     VideoOperationStatusStatus = "queued"
	VideoOperationStatusStatusGenerating VideoOperationStatusStatus = "generating"
	VideoOperationStatusStatusRendering  VideoOperationStatusStatus = "rendering"
	VideoOperationStatusStatusDone       VideoOperationStatusStatus = "done"
	VideoOperationStatusStatusError      VideoOperationStatusStatus = "error"
)

func (r VideoOperationStatusStatus) IsKnown() bool {
	switch r {
	case VideoOperationStatusStatusQueued, VideoOperationStatusStatusGenerating, VideoOperationStatusStatusRendering, VideoOperationStatusStatusDone, VideoOperationStatusStatusError:
		return true
	}
	return false
}

type AIAdListGeneratedResponse struct {
	Data []VideoOperationStatus        `json:"data"`
	JSON aiAdListGeneratedResponseJSON `json:"-"`
	PaginatedList
}

// aiAdListGeneratedResponseJSON contains the JSON metadata for the struct
// [AIAdListGeneratedResponse]
type aiAdListGeneratedResponseJSON struct {
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *AIAdListGeneratedResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r aiAdListGeneratedResponseJSON) RawJSON() string {
	return r.raw
}

type AIAdListGeneratedParams struct {
	// Maximum number of items to return in a single page.
	Limit param.Field[interface{}] `query:"limit"`
	// Number of items to skip before starting to collect the result set.
	Offset param.Field[interface{}] `query:"offset"`
	// Filter ads by their generation status.
	Status param.Field[AIAdListGeneratedParamsStatus] `query:"status"`
}

// URLQuery serializes [AIAdListGeneratedParams]'s query parameters as
// `url.Values`.
func (r AIAdListGeneratedParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

// Filter ads by their generation status.
type AIAdListGeneratedParamsStatus string

const (
	AIAdListGeneratedParamsStatusQueued     AIAdListGeneratedParamsStatus = "queued"
	AIAdListGeneratedParamsStatusGenerating AIAdListGeneratedParamsStatus = "generating"
	AIAdListGeneratedParamsStatusDone       AIAdListGeneratedParamsStatus = "done"
	AIAdListGeneratedParamsStatusError      AIAdListGeneratedParamsStatus = "error"
)

func (r AIAdListGeneratedParamsStatus) IsKnown() bool {
	switch r {
	case AIAdListGeneratedParamsStatusQueued, AIAdListGeneratedParamsStatusGenerating, AIAdListGeneratedParamsStatusDone, AIAdListGeneratedParamsStatusError:
		return true
	}
	return false
}
