// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package jamesburvelocallaghaniiicitibankdemobusinessinc

import (
	"context"
	"fmt"
	"net/http"
	"slices"

	"github.com/jocall3/1231-go/internal/apijson"
	"github.com/jocall3/1231-go/internal/param"
	"github.com/jocall3/1231-go/internal/requestconfig"
	"github.com/jocall3/1231-go/option"
)

// CorporateComplianceAuditService contains methods and other services that help
// with interacting with the 1231 API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewCorporateComplianceAuditService] method instead.
type CorporateComplianceAuditService struct {
	Options []option.RequestOption
}

// NewCorporateComplianceAuditService generates a new service that applies the
// given options to each request. These options are applied after the parent
// client's options (if there is one), and before any request-specific options.
func NewCorporateComplianceAuditService(opts ...option.RequestOption) (r *CorporateComplianceAuditService) {
	r = &CorporateComplianceAuditService{}
	r.Options = opts
	return
}

// Initiates an AI-powered compliance audit for a specific period or scope,
// generating a comprehensive report detailing adherence to regulatory frameworks,
// internal policies, and flagging potential risks.
func (r *CorporateComplianceAuditService) Request(ctx context.Context, body CorporateComplianceAuditRequestParams, opts ...option.RequestOption) (res *CorporateComplianceAuditRequestResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "corporate/compliance/audits"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

// Retrieves the full report generated by an AI-driven compliance audit.
func (r *CorporateComplianceAuditService) GetReport(ctx context.Context, auditID interface{}, opts ...option.RequestOption) (res *CorporateComplianceAuditGetReportResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := fmt.Sprintf("corporate/compliance/audits/%v/report", auditID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return
}

type CorporateComplianceAuditRequestResponse struct {
	// Unique identifier for the initiated audit.
	AuditID interface{} `json:"auditId"`
	// Current status of the audit.
	Status CorporateComplianceAuditRequestResponseStatus `json:"status"`
	JSON   corporateComplianceAuditRequestResponseJSON   `json:"-"`
}

// corporateComplianceAuditRequestResponseJSON contains the JSON metadata for the
// struct [CorporateComplianceAuditRequestResponse]
type corporateComplianceAuditRequestResponseJSON struct {
	AuditID     apijson.Field
	Status      apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *CorporateComplianceAuditRequestResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r corporateComplianceAuditRequestResponseJSON) RawJSON() string {
	return r.raw
}

// Current status of the audit.
type CorporateComplianceAuditRequestResponseStatus string

const (
	CorporateComplianceAuditRequestResponseStatusInitiated  CorporateComplianceAuditRequestResponseStatus = "initiated"
	CorporateComplianceAuditRequestResponseStatusProcessing CorporateComplianceAuditRequestResponseStatus = "processing"
	CorporateComplianceAuditRequestResponseStatusCompleted  CorporateComplianceAuditRequestResponseStatus = "completed"
	CorporateComplianceAuditRequestResponseStatusFailed     CorporateComplianceAuditRequestResponseStatus = "failed"
)

func (r CorporateComplianceAuditRequestResponseStatus) IsKnown() bool {
	switch r {
	case CorporateComplianceAuditRequestResponseStatusInitiated, CorporateComplianceAuditRequestResponseStatusProcessing, CorporateComplianceAuditRequestResponseStatusCompleted, CorporateComplianceAuditRequestResponseStatusFailed:
		return true
	}
	return false
}

type CorporateComplianceAuditGetReportResponse struct {
	// Timestamp when the audit report was generated.
	AuditDate interface{} `json:"auditDate,required"`
	// Unique identifier for the compliance audit.
	AuditID interface{} `json:"auditId,required"`
	// Detailed findings, observations, and recommendations.
	Findings []CorporateComplianceAuditGetReportResponseFinding `json:"findings,required"`
	// Overall compliance score (0-100), higher is better.
	OverallComplianceScore interface{} `json:"overallComplianceScore,required"`
	// The period covered by this audit report.
	PeriodCovered CorporateComplianceAuditGetReportResponsePeriodCovered `json:"periodCovered,required"`
	// AI-generated actionable recommendations to improve compliance.
	RecommendedActions []AIInsight `json:"recommendedActions,required"`
	// Current status of the audit.
	Status CorporateComplianceAuditGetReportResponseStatus `json:"status,required"`
	// A high-level summary of the audit findings.
	Summary interface{}                                   `json:"summary,required"`
	JSON    corporateComplianceAuditGetReportResponseJSON `json:"-"`
}

// corporateComplianceAuditGetReportResponseJSON contains the JSON metadata for the
// struct [CorporateComplianceAuditGetReportResponse]
type corporateComplianceAuditGetReportResponseJSON struct {
	AuditDate              apijson.Field
	AuditID                apijson.Field
	Findings               apijson.Field
	OverallComplianceScore apijson.Field
	PeriodCovered          apijson.Field
	RecommendedActions     apijson.Field
	Status                 apijson.Field
	Summary                apijson.Field
	raw                    string
	ExtraFields            map[string]apijson.Field
}

func (r *CorporateComplianceAuditGetReportResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r corporateComplianceAuditGetReportResponseJSON) RawJSON() string {
	return r.raw
}

type CorporateComplianceAuditGetReportResponseFinding struct {
	Description interface{} `json:"description"`
	// IDs of entities related to this finding (e.g., transaction IDs).
	RelatedEntities []interface{}                                             `json:"relatedEntities,nullable"`
	Severity        CorporateComplianceAuditGetReportResponseFindingsSeverity `json:"severity"`
	Type            CorporateComplianceAuditGetReportResponseFindingsType     `json:"type"`
	JSON            corporateComplianceAuditGetReportResponseFindingJSON      `json:"-"`
}

// corporateComplianceAuditGetReportResponseFindingJSON contains the JSON metadata
// for the struct [CorporateComplianceAuditGetReportResponseFinding]
type corporateComplianceAuditGetReportResponseFindingJSON struct {
	Description     apijson.Field
	RelatedEntities apijson.Field
	Severity        apijson.Field
	Type            apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *CorporateComplianceAuditGetReportResponseFinding) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r corporateComplianceAuditGetReportResponseFindingJSON) RawJSON() string {
	return r.raw
}

type CorporateComplianceAuditGetReportResponseFindingsSeverity string

const (
	CorporateComplianceAuditGetReportResponseFindingsSeverityLow      CorporateComplianceAuditGetReportResponseFindingsSeverity = "Low"
	CorporateComplianceAuditGetReportResponseFindingsSeverityMedium   CorporateComplianceAuditGetReportResponseFindingsSeverity = "Medium"
	CorporateComplianceAuditGetReportResponseFindingsSeverityHigh     CorporateComplianceAuditGetReportResponseFindingsSeverity = "High"
	CorporateComplianceAuditGetReportResponseFindingsSeverityCritical CorporateComplianceAuditGetReportResponseFindingsSeverity = "Critical"
)

func (r CorporateComplianceAuditGetReportResponseFindingsSeverity) IsKnown() bool {
	switch r {
	case CorporateComplianceAuditGetReportResponseFindingsSeverityLow, CorporateComplianceAuditGetReportResponseFindingsSeverityMedium, CorporateComplianceAuditGetReportResponseFindingsSeverityHigh, CorporateComplianceAuditGetReportResponseFindingsSeverityCritical:
		return true
	}
	return false
}

type CorporateComplianceAuditGetReportResponseFindingsType string

const (
	CorporateComplianceAuditGetReportResponseFindingsTypeFinding        CorporateComplianceAuditGetReportResponseFindingsType = "finding"
	CorporateComplianceAuditGetReportResponseFindingsTypeObservation    CorporateComplianceAuditGetReportResponseFindingsType = "observation"
	CorporateComplianceAuditGetReportResponseFindingsTypeRecommendation CorporateComplianceAuditGetReportResponseFindingsType = "recommendation"
)

func (r CorporateComplianceAuditGetReportResponseFindingsType) IsKnown() bool {
	switch r {
	case CorporateComplianceAuditGetReportResponseFindingsTypeFinding, CorporateComplianceAuditGetReportResponseFindingsTypeObservation, CorporateComplianceAuditGetReportResponseFindingsTypeRecommendation:
		return true
	}
	return false
}

// The period covered by this audit report.
type CorporateComplianceAuditGetReportResponsePeriodCovered struct {
	EndDate   interface{}                                                `json:"endDate"`
	StartDate interface{}                                                `json:"startDate"`
	JSON      corporateComplianceAuditGetReportResponsePeriodCoveredJSON `json:"-"`
}

// corporateComplianceAuditGetReportResponsePeriodCoveredJSON contains the JSON
// metadata for the struct [CorporateComplianceAuditGetReportResponsePeriodCovered]
type corporateComplianceAuditGetReportResponsePeriodCoveredJSON struct {
	EndDate     apijson.Field
	StartDate   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *CorporateComplianceAuditGetReportResponsePeriodCovered) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r corporateComplianceAuditGetReportResponsePeriodCoveredJSON) RawJSON() string {
	return r.raw
}

// Current status of the audit.
type CorporateComplianceAuditGetReportResponseStatus string

const (
	CorporateComplianceAuditGetReportResponseStatusProcessing CorporateComplianceAuditGetReportResponseStatus = "processing"
	CorporateComplianceAuditGetReportResponseStatusCompleted  CorporateComplianceAuditGetReportResponseStatus = "completed"
	CorporateComplianceAuditGetReportResponseStatusFailed     CorporateComplianceAuditGetReportResponseStatus = "failed"
)

func (r CorporateComplianceAuditGetReportResponseStatus) IsKnown() bool {
	switch r {
	case CorporateComplianceAuditGetReportResponseStatusProcessing, CorporateComplianceAuditGetReportResponseStatusCompleted, CorporateComplianceAuditGetReportResponseStatusFailed:
		return true
	}
	return false
}

type CorporateComplianceAuditRequestParams struct {
	// The scope of the audit (e.g., all transactions, specific accounts).
	AuditScope param.Field[CorporateComplianceAuditRequestParamsAuditScope] `json:"auditScope,required"`
	// End date for the audit period (inclusive).
	EndDate param.Field[interface{}] `json:"endDate,required"`
	// List of regulatory frameworks against which to audit.
	RegulatoryFrameworks param.Field[[]CorporateComplianceAuditRequestParamsRegulatoryFramework] `json:"regulatoryFrameworks,required"`
	// Start date for the audit period (inclusive).
	StartDate param.Field[interface{}] `json:"startDate,required"`
	// Optional: Any additional context or specific areas of concern for the AI.
	AdditionalContext param.Field[interface{}] `json:"additionalContext"`
}

func (r CorporateComplianceAuditRequestParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

// The scope of the audit (e.g., all transactions, specific accounts).
type CorporateComplianceAuditRequestParamsAuditScope string

const (
	CorporateComplianceAuditRequestParamsAuditScopeAllTransactions  CorporateComplianceAuditRequestParamsAuditScope = "all_transactions"
	CorporateComplianceAuditRequestParamsAuditScopeSpecificAccounts CorporateComplianceAuditRequestParamsAuditScope = "specific_accounts"
	CorporateComplianceAuditRequestParamsAuditScopeSpecificCards    CorporateComplianceAuditRequestParamsAuditScope = "specific_cards"
	CorporateComplianceAuditRequestParamsAuditScopeAllUsers         CorporateComplianceAuditRequestParamsAuditScope = "all_users"
)

func (r CorporateComplianceAuditRequestParamsAuditScope) IsKnown() bool {
	switch r {
	case CorporateComplianceAuditRequestParamsAuditScopeAllTransactions, CorporateComplianceAuditRequestParamsAuditScopeSpecificAccounts, CorporateComplianceAuditRequestParamsAuditScopeSpecificCards, CorporateComplianceAuditRequestParamsAuditScopeAllUsers:
		return true
	}
	return false
}

type CorporateComplianceAuditRequestParamsRegulatoryFramework string

const (
	CorporateComplianceAuditRequestParamsRegulatoryFrameworkAml    CorporateComplianceAuditRequestParamsRegulatoryFramework = "AML"
	CorporateComplianceAuditRequestParamsRegulatoryFrameworkKYC    CorporateComplianceAuditRequestParamsRegulatoryFramework = "KYC"
	CorporateComplianceAuditRequestParamsRegulatoryFrameworkPciDss CorporateComplianceAuditRequestParamsRegulatoryFramework = "PCI-DSS"
	CorporateComplianceAuditRequestParamsRegulatoryFrameworkGdpr   CorporateComplianceAuditRequestParamsRegulatoryFramework = "GDPR"
	CorporateComplianceAuditRequestParamsRegulatoryFrameworkCcpa   CorporateComplianceAuditRequestParamsRegulatoryFramework = "CCPA"
	CorporateComplianceAuditRequestParamsRegulatoryFrameworkSox    CorporateComplianceAuditRequestParamsRegulatoryFramework = "SOX"
	CorporateComplianceAuditRequestParamsRegulatoryFrameworkOfac   CorporateComplianceAuditRequestParamsRegulatoryFramework = "OFAC"
)

func (r CorporateComplianceAuditRequestParamsRegulatoryFramework) IsKnown() bool {
	switch r {
	case CorporateComplianceAuditRequestParamsRegulatoryFrameworkAml, CorporateComplianceAuditRequestParamsRegulatoryFrameworkKYC, CorporateComplianceAuditRequestParamsRegulatoryFrameworkPciDss, CorporateComplianceAuditRequestParamsRegulatoryFrameworkGdpr, CorporateComplianceAuditRequestParamsRegulatoryFrameworkCcpa, CorporateComplianceAuditRequestParamsRegulatoryFrameworkSox, CorporateComplianceAuditRequestParamsRegulatoryFrameworkOfac:
		return true
	}
	return false
}
