// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package jamesburvelocallaghaniiicitibankdemobusinessinc

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"
	"time"

	"github.com/stainless-sdks/1231-go/internal/apijson"
	"github.com/stainless-sdks/1231-go/internal/param"
	"github.com/stainless-sdks/1231-go/internal/requestconfig"
	"github.com/stainless-sdks/1231-go/option"
)

// CorporateComplianceAuditService contains methods and other services that help
// with interacting with the 1231 API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewCorporateComplianceAuditService] method instead.
type CorporateComplianceAuditService struct {
	Options []option.RequestOption
}

// NewCorporateComplianceAuditService generates a new service that applies the
// given options to each request. These options are applied after the parent
// client's options (if there is one), and before any request-specific options.
func NewCorporateComplianceAuditService(opts ...option.RequestOption) (r *CorporateComplianceAuditService) {
	r = &CorporateComplianceAuditService{}
	r.Options = opts
	return
}

// Initiates an AI-powered compliance audit for a specific period or scope,
// generating a comprehensive report detailing adherence to regulatory frameworks,
// internal policies, and flagging potential risks.
func (r *CorporateComplianceAuditService) Request(ctx context.Context, body CorporateComplianceAuditRequestParams, opts ...option.RequestOption) (res *CorporateComplianceAuditRequestResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "corporate/compliance/audits"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

// Retrieves the full report generated by an AI-driven compliance audit.
func (r *CorporateComplianceAuditService) GetReport(ctx context.Context, auditID string, opts ...option.RequestOption) (res *CorporateComplianceAuditGetReportResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if auditID == "" {
		err = errors.New("missing required auditId parameter")
		return
	}
	path := fmt.Sprintf("corporate/compliance/audits/%s/report", auditID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return
}

type CorporateComplianceAuditRequestResponse struct {
	AuditID string                                        `json:"auditId"`
	Status  CorporateComplianceAuditRequestResponseStatus `json:"status"`
	JSON    corporateComplianceAuditRequestResponseJSON   `json:"-"`
}

// corporateComplianceAuditRequestResponseJSON contains the JSON metadata for the
// struct [CorporateComplianceAuditRequestResponse]
type corporateComplianceAuditRequestResponseJSON struct {
	AuditID     apijson.Field
	Status      apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *CorporateComplianceAuditRequestResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r corporateComplianceAuditRequestResponseJSON) RawJSON() string {
	return r.raw
}

type CorporateComplianceAuditRequestResponseStatus string

const (
	CorporateComplianceAuditRequestResponseStatusProcessing CorporateComplianceAuditRequestResponseStatus = "processing"
	CorporateComplianceAuditRequestResponseStatusCompleted  CorporateComplianceAuditRequestResponseStatus = "completed"
	CorporateComplianceAuditRequestResponseStatusFailed     CorporateComplianceAuditRequestResponseStatus = "failed"
)

func (r CorporateComplianceAuditRequestResponseStatus) IsKnown() bool {
	switch r {
	case CorporateComplianceAuditRequestResponseStatusProcessing, CorporateComplianceAuditRequestResponseStatusCompleted, CorporateComplianceAuditRequestResponseStatusFailed:
		return true
	}
	return false
}

type CorporateComplianceAuditGetReportResponse struct {
	AuditDate              time.Time                                              `json:"auditDate" format:"date-time"`
	AuditID                string                                                 `json:"auditId"`
	Findings               []CorporateComplianceAuditGetReportResponseFinding     `json:"findings"`
	OverallComplianceScore int64                                                  `json:"overallComplianceScore"`
	PeriodCovered          CorporateComplianceAuditGetReportResponsePeriodCovered `json:"periodCovered"`
	RecommendedActions     []AIInsight                                            `json:"recommendedActions"`
	Status                 string                                                 `json:"status"`
	Summary                string                                                 `json:"summary"`
	JSON                   corporateComplianceAuditGetReportResponseJSON          `json:"-"`
}

// corporateComplianceAuditGetReportResponseJSON contains the JSON metadata for the
// struct [CorporateComplianceAuditGetReportResponse]
type corporateComplianceAuditGetReportResponseJSON struct {
	AuditDate              apijson.Field
	AuditID                apijson.Field
	Findings               apijson.Field
	OverallComplianceScore apijson.Field
	PeriodCovered          apijson.Field
	RecommendedActions     apijson.Field
	Status                 apijson.Field
	Summary                apijson.Field
	raw                    string
	ExtraFields            map[string]apijson.Field
}

func (r *CorporateComplianceAuditGetReportResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r corporateComplianceAuditGetReportResponseJSON) RawJSON() string {
	return r.raw
}

type CorporateComplianceAuditGetReportResponseFinding struct {
	Description     string                                                    `json:"description"`
	RelatedEntities []string                                                  `json:"relatedEntities"`
	Severity        CorporateComplianceAuditGetReportResponseFindingsSeverity `json:"severity"`
	Type            CorporateComplianceAuditGetReportResponseFindingsType     `json:"type"`
	JSON            corporateComplianceAuditGetReportResponseFindingJSON      `json:"-"`
}

// corporateComplianceAuditGetReportResponseFindingJSON contains the JSON metadata
// for the struct [CorporateComplianceAuditGetReportResponseFinding]
type corporateComplianceAuditGetReportResponseFindingJSON struct {
	Description     apijson.Field
	RelatedEntities apijson.Field
	Severity        apijson.Field
	Type            apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *CorporateComplianceAuditGetReportResponseFinding) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r corporateComplianceAuditGetReportResponseFindingJSON) RawJSON() string {
	return r.raw
}

type CorporateComplianceAuditGetReportResponseFindingsSeverity string

const (
	CorporateComplianceAuditGetReportResponseFindingsSeverityLow    CorporateComplianceAuditGetReportResponseFindingsSeverity = "Low"
	CorporateComplianceAuditGetReportResponseFindingsSeverityMedium CorporateComplianceAuditGetReportResponseFindingsSeverity = "Medium"
	CorporateComplianceAuditGetReportResponseFindingsSeverityHigh   CorporateComplianceAuditGetReportResponseFindingsSeverity = "High"
)

func (r CorporateComplianceAuditGetReportResponseFindingsSeverity) IsKnown() bool {
	switch r {
	case CorporateComplianceAuditGetReportResponseFindingsSeverityLow, CorporateComplianceAuditGetReportResponseFindingsSeverityMedium, CorporateComplianceAuditGetReportResponseFindingsSeverityHigh:
		return true
	}
	return false
}

type CorporateComplianceAuditGetReportResponseFindingsType string

const (
	CorporateComplianceAuditGetReportResponseFindingsTypeViolation      CorporateComplianceAuditGetReportResponseFindingsType = "violation"
	CorporateComplianceAuditGetReportResponseFindingsTypeRecommendation CorporateComplianceAuditGetReportResponseFindingsType = "recommendation"
	CorporateComplianceAuditGetReportResponseFindingsTypeObservation    CorporateComplianceAuditGetReportResponseFindingsType = "observation"
)

func (r CorporateComplianceAuditGetReportResponseFindingsType) IsKnown() bool {
	switch r {
	case CorporateComplianceAuditGetReportResponseFindingsTypeViolation, CorporateComplianceAuditGetReportResponseFindingsTypeRecommendation, CorporateComplianceAuditGetReportResponseFindingsTypeObservation:
		return true
	}
	return false
}

type CorporateComplianceAuditGetReportResponsePeriodCovered struct {
	EndDate   time.Time                                                  `json:"endDate" format:"date"`
	StartDate time.Time                                                  `json:"startDate" format:"date"`
	JSON      corporateComplianceAuditGetReportResponsePeriodCoveredJSON `json:"-"`
}

// corporateComplianceAuditGetReportResponsePeriodCoveredJSON contains the JSON
// metadata for the struct [CorporateComplianceAuditGetReportResponsePeriodCovered]
type corporateComplianceAuditGetReportResponsePeriodCoveredJSON struct {
	EndDate     apijson.Field
	StartDate   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *CorporateComplianceAuditGetReportResponsePeriodCovered) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r corporateComplianceAuditGetReportResponsePeriodCoveredJSON) RawJSON() string {
	return r.raw
}

type CorporateComplianceAuditRequestParams struct {
	AuditScope           param.Field[string]    `json:"auditScope,required"`
	EndDate              param.Field[time.Time] `json:"endDate,required" format:"date"`
	StartDate            param.Field[time.Time] `json:"startDate,required" format:"date"`
	RegulatoryFrameworks param.Field[[]string]  `json:"regulatoryFrameworks"`
}

func (r CorporateComplianceAuditRequestParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}
