// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package jamesburvelocallaghaniiicitibankdemobusinessinc

import (
	"context"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/stainless-sdks/1231-go/internal/apijson"
	"github.com/stainless-sdks/1231-go/internal/apiquery"
	"github.com/stainless-sdks/1231-go/internal/param"
	"github.com/stainless-sdks/1231-go/internal/requestconfig"
	"github.com/stainless-sdks/1231-go/option"
)

// LendingOfferService contains methods and other services that help with
// interacting with the 1231 API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewLendingOfferService] method instead.
type LendingOfferService struct {
	Options []option.RequestOption
}

// NewLendingOfferService generates a new service that applies the given options to
// each request. These options are applied after the parent client's options (if
// there is one), and before any request-specific options.
func NewLendingOfferService(opts ...option.RequestOption) (r *LendingOfferService) {
	r = &LendingOfferService{}
	r.Options = opts
	return
}

// Retrieves a list of personalized, pre-approved loan offers generated by the AI
// based on the user's financial profile and credit health.
func (r *LendingOfferService) ListPreApproved(ctx context.Context, query LendingOfferListPreApprovedParams, opts ...option.RequestOption) (res *LendingOfferListPreApprovedResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "lending/offers/pre-approved"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return
}

type LoanOffer struct {
	AIPersonalizationScore float64       `json:"aiPersonalizationScore"`
	Amount                 float64       `json:"amount"`
	ExpirationDate         time.Time     `json:"expirationDate" format:"date"`
	InterestRate           float64       `json:"interestRate"`
	IsPreApproved          bool          `json:"isPreApproved"`
	MonthlyPayment         float64       `json:"monthlyPayment"`
	OfferID                string        `json:"offerId"`
	OfferType              string        `json:"offerType"`
	OriginationFee         float64       `json:"originationFee"`
	RepaymentTermMonths    int64         `json:"repaymentTermMonths"`
	TotalRepayable         float64       `json:"totalRepayable"`
	JSON                   loanOfferJSON `json:"-"`
}

// loanOfferJSON contains the JSON metadata for the struct [LoanOffer]
type loanOfferJSON struct {
	AIPersonalizationScore apijson.Field
	Amount                 apijson.Field
	ExpirationDate         apijson.Field
	InterestRate           apijson.Field
	IsPreApproved          apijson.Field
	MonthlyPayment         apijson.Field
	OfferID                apijson.Field
	OfferType              apijson.Field
	OriginationFee         apijson.Field
	RepaymentTermMonths    apijson.Field
	TotalRepayable         apijson.Field
	raw                    string
	ExtraFields            map[string]apijson.Field
}

func (r *LoanOffer) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r loanOfferJSON) RawJSON() string {
	return r.raw
}

type LendingOfferListPreApprovedResponse struct {
	Data []LoanOffer                             `json:"data"`
	JSON lendingOfferListPreApprovedResponseJSON `json:"-"`
	PaginatedList
}

// lendingOfferListPreApprovedResponseJSON contains the JSON metadata for the
// struct [LendingOfferListPreApprovedResponse]
type lendingOfferListPreApprovedResponseJSON struct {
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *LendingOfferListPreApprovedResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r lendingOfferListPreApprovedResponseJSON) RawJSON() string {
	return r.raw
}

type LendingOfferListPreApprovedParams struct {
	// The maximum number of items to return.
	Limit param.Field[int64] `query:"limit"`
	// The number of items to skip before starting to collect the result set.
	Offset param.Field[int64] `query:"offset"`
}

// URLQuery serializes [LendingOfferListPreApprovedParams]'s query parameters as
// `url.Values`.
func (r LendingOfferListPreApprovedParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}
