// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package jocall3

import (
	"context"
	"net/http"
	"net/url"
	"slices"

	"github.com/jocall3/go/internal/apijson"
	"github.com/jocall3/go/internal/apiquery"
	"github.com/jocall3/go/internal/param"
	"github.com/jocall3/go/internal/requestconfig"
	"github.com/jocall3/go/option"
)

// LendingOfferService contains methods and other services that help with
// interacting with the 1231 API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewLendingOfferService] method instead.
type LendingOfferService struct {
	Options []option.RequestOption
}

// NewLendingOfferService generates a new service that applies the given options to
// each request. These options are applied after the parent client's options (if
// there is one), and before any request-specific options.
func NewLendingOfferService(opts ...option.RequestOption) (r *LendingOfferService) {
	r = &LendingOfferService{}
	r.Options = opts
	return
}

// Retrieves a list of personalized, pre-approved loan offers generated by the AI
// based on the user's financial profile and credit health.
func (r *LendingOfferService) ListPreApproved(ctx context.Context, query LendingOfferListPreApprovedParams, opts ...option.RequestOption) (res *LendingOfferListPreApprovedResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "lending/offers/pre-approved"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return
}

type LoanOffer struct {
	// The offered loan amount.
	Amount interface{} `json:"amount,required"`
	// Date the offer expires.
	ExpirationDate interface{} `json:"expirationDate,required"`
	// Annual interest rate offered (as a percentage).
	InterestRate interface{} `json:"interestRate,required"`
	// Indicates if this is a pre-approved offer.
	IsPreApproved interface{} `json:"isPreApproved,required"`
	// Unique identifier for the loan offer.
	OfferID interface{} `json:"offerId,required"`
	// Type of loan being offered.
	OfferType LoanOfferOfferType `json:"offerType,required"`
	// AI's score for how well this offer is personalized to the user (0-1).
	AIPersonalizationScore interface{} `json:"aiPersonalizationScore"`
	// Estimated monthly payment (if applicable).
	MonthlyPayment interface{} `json:"monthlyPayment"`
	// Any origination fees for the loan.
	OriginationFee interface{} `json:"originationFee"`
	// Repayment term in months (if applicable).
	RepaymentTermMonths interface{} `json:"repaymentTermMonths"`
	// URL to the full terms and conditions of the loan offer.
	TermsAndConditionsURL interface{} `json:"termsAndConditionsUrl"`
	// Total amount repayable over the loan term.
	TotalRepayable interface{}   `json:"totalRepayable"`
	JSON           loanOfferJSON `json:"-"`
}

// loanOfferJSON contains the JSON metadata for the struct [LoanOffer]
type loanOfferJSON struct {
	Amount                 apijson.Field
	ExpirationDate         apijson.Field
	InterestRate           apijson.Field
	IsPreApproved          apijson.Field
	OfferID                apijson.Field
	OfferType              apijson.Field
	AIPersonalizationScore apijson.Field
	MonthlyPayment         apijson.Field
	OriginationFee         apijson.Field
	RepaymentTermMonths    apijson.Field
	TermsAndConditionsURL  apijson.Field
	TotalRepayable         apijson.Field
	raw                    string
	ExtraFields            map[string]apijson.Field
}

func (r *LoanOffer) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r loanOfferJSON) RawJSON() string {
	return r.raw
}

// Type of loan being offered.
type LoanOfferOfferType string

const (
	LoanOfferOfferTypePersonalLoan LoanOfferOfferType = "personal_loan"
	LoanOfferOfferTypeAutoLoan     LoanOfferOfferType = "auto_loan"
	LoanOfferOfferTypeMortgage     LoanOfferOfferType = "mortgage"
	LoanOfferOfferTypeCreditLine   LoanOfferOfferType = "credit_line"
	LoanOfferOfferTypeMicroloan    LoanOfferOfferType = "microloan"
)

func (r LoanOfferOfferType) IsKnown() bool {
	switch r {
	case LoanOfferOfferTypePersonalLoan, LoanOfferOfferTypeAutoLoan, LoanOfferOfferTypeMortgage, LoanOfferOfferTypeCreditLine, LoanOfferOfferTypeMicroloan:
		return true
	}
	return false
}

type LendingOfferListPreApprovedResponse struct {
	Data []LoanOffer                             `json:"data"`
	JSON lendingOfferListPreApprovedResponseJSON `json:"-"`
	PaginatedList
}

// lendingOfferListPreApprovedResponseJSON contains the JSON metadata for the
// struct [LendingOfferListPreApprovedResponse]
type lendingOfferListPreApprovedResponseJSON struct {
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *LendingOfferListPreApprovedResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r lendingOfferListPreApprovedResponseJSON) RawJSON() string {
	return r.raw
}

type LendingOfferListPreApprovedParams struct {
	// Maximum number of items to return in a single page.
	Limit param.Field[interface{}] `query:"limit"`
	// Number of items to skip before starting to collect the result set.
	Offset param.Field[interface{}] `query:"offset"`
}

// URLQuery serializes [LendingOfferListPreApprovedParams]'s query parameters as
// `url.Values`.
func (r LendingOfferListPreApprovedParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}
